### ISSUE TITLE
Converting phylip files to nexus format

### ISSUE THREAD

**Issue by j-chou** [j-chou/svdquartets#3]
There's a problem in PAUP that prevents me from converting phylip files to nexus format, so I needed to use a Python library bioscripts to convert them. It took about 2 hours though on my machine to convert 10 folders of alignments (corresponding to 10 species trees) and we have over 200 folders to convert. I'll contact help at CC to ask if I can install the bioscripts package on the CC so that I can do the conversions on the CC.

**Comment by redavids** [comment]
Have you reported to PAUP?

I think your problem resolution strategy is fine, but that is the sort of
thing they would love to know.

Also, when I had to install R package to get NJst running i only had to do
it once.  Try installing your bioscripts library in home/jchou (your name)
and see if it works then.    If it is a fast import, you can add it to your
.bashrc file so it always loads when you log in too. ..

On Thu, Apr 2, 2015 at 1:00 PM, j-chou <notifications@github.com> wrote:

> There's a problem in PAUP that prevents me from converting phylip files to
> nexus format, so I needed to use a Python library bioscripts to convert
> them. It took about 2 hours though on my machine to convert 10 folders of
> alignments (corresponding to 10 species trees) and we have over 200 folders
> to convert. I'll contact help at CC to ask if I can install the bioscripts
> package on the CC so that I can do the conversions on the CC.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/j-chou/svdquartets/issues/3>.
>



-- 
Ruth Davidson
Department of Mathematics, University of Illinois Urbana-Champaign
http://www.math.uiuc.edu/~redavid2/

**Comment by j-chou** [comment]
Ah ok, I'll report it to PAUP. Thanks! I got it to work. I'll start converting the files to nexus and getting gene trees files with fastTree.

**Comment by redavids** [comment]
That's good to practice!  But remember we'll need to have you do that on
short samples of columns from the full genes-

On Thu, Apr 2, 2015 at 1:41 PM, j-chou <notifications@github.com> wrote:

> Ah ok, I'll report it to PAUP. Thanks! I got it to work. I'll start
> converting the files to nexus and getting gene trees files with fastTree.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/j-chou/svdquartets/issues/3#issuecomment-89005383>.
>



-- 
Ruth Davidson
Department of Mathematics, University of Illinois Urbana-Champaign
http://www.math.uiuc.edu/~redavid2/
